name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install LLVM and Ninja
        run: choco install llvm ninja --no-progress

      - name: Build
        run: |
          cmake -G Ninja -DCMAKE_C_COMPILER=clang-cl -DCMAKE_BUILD_TYPE=RelWithDebInfo -S . -B build
          cmake --build build -j

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: endstone_mediaplayer-windows
          path: |
            build/endstone_mediaplayer.dll
            build/endstone_mediaplayer.pdb
          retention-days: 1

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install LLVM and Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld ninja-build

      - name: Build
        run: |
          cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=RelWithDebInfo -S . -B build
          cmake --build build --parallel

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: endstone_mediaplayer-linux
          path: build/endstone_mediaplayer.so
          retention-days: 1

  sanitize-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install LLVM and Ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld ninja-build

      - name: Build with sanitizers
        run: |
          cmake -G Ninja \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_BUILD_TYPE=Debug \
            -DENABLE_SANITIZER=ON \
            -S . -B build-sanitized
          cmake --build build-sanitized --parallel

      - name: Run sanitized tests
        run: |
          ASAN_OPTIONS=detect_leaks=1 \
          ctest --test-dir build-sanitized --output-on-failure

  package:
    needs: [build-win, build-linux, sanitize-linux]
    runs-on: ubuntu-22.04
    steps:
      - name: Download build files
        uses: actions/download-artifact@v7
        with:
          pattern: endstone_mediaplayer-*
          path: artifact
          merge-multiple: true

      - name: Upload combined artifact
        uses: actions/upload-artifact@v7
        with:
          name: endstone_mediaplayer
          path: |
            artifact/endstone_mediaplayer.dll
            artifact/endstone_mediaplayer.pdb
            artifact/endstone_mediaplayer.so